### ISSUE TITLE
Question: How to update docker image

### ISSUE THREAD

**Issue by pouldam** [pfink/nuimo-raspbian-docker#1]
I can see that the nuimo-openhab project has been updated recently. What is the best way to update the docker image to include the newest version of the nuimo-openhab project?

**Comment by pfink** [comment]
First of all, when you use _Raspbian Stretch_ which was recently released, the docker container is hopefully not needed anymore as the bluez version of Stretch should be new enough. Nevertheless, there are two cases:

1. You want to upgrade to a new version of a released docker container update: This is described very well here: https://stackoverflow.com/questions/26734402/how-to-upgrade-docker-container-after-its-image-changed. But currently, there is no new release version.
1.  You want to update to the newest development version even if there is no new release yet (I think that is what you meant with your question): There are two ways to do it.
    1.  The "Docker Way": Create an updated version of the container with the `docker build` command as shown in the README. As this consumes very much time when you do it the first time because bluez has to be built, there is also a "hacky way".
    1. Update the application within the existing docker container: There is a volume for the nuimo-openhab-python library mounted on the host system. This Stackoverflow answer describes how you can find it: https://stackoverflow.com/a/30133768. After you found the volume, you can just run `git pull` within the volume path + `docker restart <container_id>` and you're all done.

**Comment by pfink** [comment]
P.S.: If you can successfully test it directly on _Stretch_ without a docker container, please notify me so that I can update the docs of the nuimo-openhab-python library.

**Comment by pouldam** [comment]
Hi, thanks for getting back with the detailed answer. I will consider trying to upgrade to Stretch when I have some more time.

What I really wanted, was to update the nuimo-openhab-python application running inside the Docker container as I saw you had made some changes. I know too little about Docker and Git, but my guess would be, that you have to issue a command that pulls the newest files from Github. Something like:

`docker exec nuimo-openhab git pull`

But I am not sure... guess I have to tell Git where to do the pull...

**Comment by pfink** [comment]
@pouldam: Yes, I described this solution in 2. ii. you have to find the volume, than you have to `cd` to this volume and run `git pull`.

**Comment by pouldam** [comment]
Thanks and sorry - I have no idea how I missed that!
